In [ ]:
import pandas as pd
df=pd.read_csv("test_data.csv")
print(df)

       id first_name  last_name                      email      gender  \
0       1     Karoly      Hodge            khodge0@icq.com        Male
1       2       Mala    Balogun    mbalogun1@artisteer.com      Female
2       3       Cati     Ferrie    cferrie2@techcrunch.com         NaN
3       4    Felecia   Gentreau  fgentreau3@purevolume.com  Non-binary
4       5   Winthrop   McKinley    wmckinley4@usatoday.com         NaN
..    ...        ...        ...                        ...         ...
995   996       Alon    Cockney  acockneyrn@mayoclinic.com        Male
996   997     Brocky     Dumbar  bdumbarro@liveinternet.ru        Male
997   998     Margot  Kingscott       mkingscottrp@mac.com    Bigender
998   999    Zabrina     Holgan           zholganrq@si.edu      Female
999  1000  Valentine    Purslow       vpurslowrr@chron.com        Male

        car model
0             NaN
1             MKZ
2    Ram Van B250
3              RX
4              ES
..            ...
995         Tempo
996        SJ 410
997       Samurai
998            X3
999           NaN

[1000 rows x 6 columns]

In [ ]:
import pandas as pd
df=pd.read_csv('test_data.csv')
hd=df.head()

In [ ]:
df=pd.read_csv('test_data.csv')
tl=df.tail()
print(tl)

       id first_name  last_name                      email    gender car model
995   996       Alon    Cockney  acockneyrn@mayoclinic.com      Male     Tempo
996   997     Brocky     Dumbar  bdumbarro@liveinternet.ru      Male    SJ 410
997   998     Margot  Kingscott       mkingscottrp@mac.com  Bigender   Samurai
998   999    Zabrina     Holgan           zholganrq@si.edu    Female        X3
999  1000  Valentine    Purslow       vpurslowrr@chron.com      Male       NaN

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          1000 non-null   int64
 1   first_name  1000 non-null   object
 2   last_name   1000 non-null   object
 3   email       1000 non-null   object
 4   gender      791 non-null    object
 5   car model   777 non-null    object
dtypes: int64(1), object(5)
memory usage: 47.0+ KB

In [ ]:
df.describe()

                id
count  1000.000000
mean    500.500000
std     288.819436
min       1.000000
25%     250.750000
50%     500.500000
75%     750.250000
max    1000.000000

#cleaning data,checking empty/null csll values

In [ ]:
# cl=df.dropna()
# print(cl.to_string())

In [ ]:
x=df['gender'].mode()[0]
df['gender'].fillna(x,inplace=True)
print(df.to_string)

<bound method DataFrame.to_string of        id first_name  last_name                      email      gender  \
0       1     Karoly      Hodge            khodge0@icq.com        Male
1       2       Mala    Balogun    mbalogun1@artisteer.com      Female
2       3       Cati     Ferrie    cferrie2@techcrunch.com      Female
3       4    Felecia   Gentreau  fgentreau3@purevolume.com  Non-binary
4       5   Winthrop   McKinley    wmckinley4@usatoday.com      Female
..    ...        ...        ...                        ...         ...
995   996       Alon    Cockney  acockneyrn@mayoclinic.com        Male
996   997     Brocky     Dumbar  bdumbarro@liveinternet.ru        Male
997   998     Margot  Kingscott       mkingscottrp@mac.com    Bigender
998   999    Zabrina     Holgan           zholganrq@si.edu      Female
999  1000  Valentine    Purslow       vpurslowrr@chron.com        Male

        car model
0             NaN
1             MKZ
2    Ram Van B250
3              RX
4              ES
..            ...
995         Tempo
996        SJ 410
997       Samurai
998            X3
999           NaN

[1000 rows x 6 columns]>

#New questian

In [ ]:
import pandas as pd
df=pd.read_csv('test4.csv')
print(df)

     sales_id product_name  sales_date  quantity_sold  unit_price  \
0           1    Product B   1/16/2022            788      450.32
1           2    Product C   9/30/2022            690       19.23
2           3    Product B  11/19/2022            689      131.28
3           4    Product C  11/26/2022            736      107.81
4           5    Product B  10/29/2022            277      639.89
..        ...          ...         ...            ...         ...
995       996    Product C    8/3/2022            105      449.45
996       997    Product B   1/11/2022            330      308.02
997       998    Product C  10/15/2022            209      477.32
998       999    Product A    7/9/2022             71       67.77
999      1000    Product B   3/20/2022            721      197.25

     total_profit
0       354852.16
1        13268.70
2        90451.92
3        79348.16
4       177249.53
..            ...
995      47192.25
996     101646.60
997      99759.88
998       4811.67
999     142217.25

[1000 rows x 6 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   sales_id       1000 non-null   int64
 1   product_name   1000 non-null   object
 2   sales_date     1000 non-null   object
 3   quantity_sold  1000 non-null   int64
 4   unit_price     1000 non-null   float64
 5   total_profit   1000 non-null   float64
dtypes: float64(2), int64(2), object(2)
memory usage: 47.0+ KB

In [ ]:
df.describe()

          sales_id  quantity_sold   unit_price   total_profit
count  1000.000000    1000.000000  1000.000000    1000.000000
mean    500.500000     503.601000   507.048240  257026.715000
std     288.819436     289.927131   289.078096  227493.632423
min       1.000000       2.000000     0.840000     144.480000
25%     250.750000     258.750000   262.285000   71097.240000
50%     500.500000     501.500000   504.700000  194059.070000
75%     750.250000     758.250000   755.857500  373913.442500
max    1000.000000    1000.000000   999.850000  975560.600000

In [ ]:
df["sales_date"]=pd.to_datetime(df["sales_date"])
df

     sales_id product_name sales_date  quantity_sold  unit_price  total_profit
0           1    Product B 2022-01-16            788      450.32     354852.16
1           2    Product C 2022-09-30            690       19.23      13268.70
2           3    Product B 2022-11-19            689      131.28      90451.92
3           4    Product C 2022-11-26            736      107.81      79348.16
4           5    Product B 2022-10-29            277      639.89     177249.53
..        ...          ...        ...            ...         ...           ...
995       996    Product C 2022-08-03            105      449.45      47192.25
996       997    Product B 2022-01-11            330      308.02     101646.60
997       998    Product C 2022-10-15            209      477.32      99759.88
998       999    Product A 2022-07-09             71       67.77       4811.67
999      1000    Product B 2022-03-20            721      197.25     142217.25

[1000 rows x 6 columns]

In [ ]:
df.shape

(1000, 6)

In [ ]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997    False
998    False
999    False
Length: 1000, dtype: bool

In [ ]:
df.drop_duplicates()

     sales_id product_name sales_date  quantity_sold  unit_price  total_profit
0           1    Product B 2022-01-16            788      450.32     354852.16
1           2    Product C 2022-09-30            690       19.23      13268.70
2           3    Product B 2022-11-19            689      131.28      90451.92
3           4    Product C 2022-11-26            736      107.81      79348.16
4           5    Product B 2022-10-29            277      639.89     177249.53
..        ...          ...        ...            ...         ...           ...
995       996    Product C 2022-08-03            105      449.45      47192.25
996       997    Product B 2022-01-11            330      308.02     101646.60
997       998    Product C 2022-10-15            209      477.32      99759.88
998       999    Product A 2022-07-09             71       67.77       4811.67
999      1000    Product B 2022-03-20            721      197.25     142217.25

[1000 rows x 6 columns]

In [ ]:
x=df.select_dtypes(include=["number"])
x.corr()

               sales_id  quantity_sold  unit_price  total_profit
sales_id       1.000000      -0.064180    0.034405     -0.006309
quantity_sold -0.064180       1.000000    0.020026      0.674741
unit_price     0.034405       0.020026    1.000000      0.653744
total_profit  -0.006309       0.674741    0.653744      1.000000